### ISSUE TITLE
[BUG]: Docker images not supporting platform  linux/arm64/v8

### ISSUE THREAD

**Issue by manojLondhe** [Sunbird-RC/community#671]
### What is the bug related to?

Registry Core

### What went wrong?

When using docker images on Apple Macbook Air M1, getting warnings as below

```
⠴ keycloak The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
⠴ registry The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
```

- Keycloak image does not work
- Registry image is too slow

### What did you expect to see?

Docker images to support platform  linux/arm64/v8

### Additional Context

Additionally noted that Dockerfile not present in [Keycloak repo](https://github.com/search?q=repo%3ASunbird-RC%2Fkeycloak%20Dockerfile&type=code)

**Comment by holashchand** [comment]
PR resolving this issue: https://github.com/Sunbird-RC/sunbird-rc-core/pull/260

**Comment by srprasanna** [comment]
@itsvick can you also share some documentation of the changes that you have done. @holashchand if we need to build and publish a new keycloak revision, please ensure that this is done as well.

**Comment by holashchand** [comment]
@srprasanna `vikastc/sunbirdrc-keycloak:apple-silicon` is Apple M1 keycloak base image which is required to build sunbird-rc-keycloak revision. Using that base image the keycloak image can be built from our systems as well. This should be published as new revision, since base images are different. we can push that image to git packages and then reference if we don't want base image to be maintained on dockerhub.

The below steps can be followed -
1. Move base image vikastc/sunbirdrc-keycloak:apple-silicon to git packages
2. Build and publish new revision of sunbird-rc-keycloak specific for Apple silicon versions.

The image was tested and working fine! :+1:
