### ISSUE TITLE
[BUG]: Certificate Text Alignment getting change after adding schema fields through advance editor

### ISSUE THREAD

**Issue by Pritzz4** [Sunbird-RC/community#688]
**Steps to reproduce**

- Click on add new document
- Click on my template 
- upload the SVG/Html file 
- Click on edit template button
- Click on save document button
- Click on Ok - (it will redirect to advance editor page)
- Add the schema fields 
- Click on save 

**Before Adding Schema fields**
![Image](https://github.com/Sunbird-RC/community/assets/118895138/e719f64f-3f9e-49ae-bee1-486e8226f800)

**After Adding schema fields**
![Image](https://github.com/Sunbird-RC/community/assets/118895138/9b7b5e5b-ba87-4631-91ab-6fbb75e044c6)

**Comment by suvarnakale** [comment]
**Root Cause:**
- The alignment issue occurs due to conflicting CSS styles between the grapeJS library and the form builder. Upon saving the template, certain CSS rules from the form builder override or modify the styles applied by the grapeJS library, resulting in the misalignment of the certificate.
