### ISSUE TITLE
Create javascript SDK for verification App

### ISSUE THREAD

**Issue by Sreejit-K** [Sunbird-RC/community#909]
### What is the feature request for?

Others

### Verification sdk:
**Purpose of this sdk:**
The aim is to create a common utility package so that new users who are trying to create their own Verifier app can just import this as a npm package and have the vc validation code functionality right away.
	
Cururently, the library exports the following method:

**validateVC(vc, options)**
> **vc** - the verfiable credetntials
> **options** - valid issuers, ignore expiry date, etc. and more options as needed (maybe looking for a particular attributes in the vc, for example)

**Verification process:**
- get public key using did
- validate the vc - signature
- validate metadata - check for expiry time, issuer, etc. fields
- validate options if passed
- check if the vc is revoked

### Describe the feature clearly.

https://digit-discuss.atlassian.net/browse/DPG-2159

**Comment by manukalia29** [comment]
@shiva-beehyv Please add description

**Comment by shiva-beehyv** [comment]
### Verification sdk:
**Purpose of this sdk:**
The aim is to create a common utility package so that new users who are trying to create their own Verifier app can just import this as a npm package and have the vc validation code functionality right away.
	
Cururently, the library exports the following method:

**validateVC(vc, options)**
> **vc** - the verfiable credetntials
> **options** - valid issuers, ignore expiry date, etc. and more options as needed (maybe looking for a particular attributes in the vc, for example)

**Verification process:**
- get public key using did
- validate the vc - signature
- validate metadata - check for expiry time, issuer, etc. fields
- validate options if passed
- check if the vc is revoked

**Comment by srprasanna** [comment]
Let's also look at downloading revocation list, which will be mentioned in the URL. @shiva-beehyv can you also list function signatures and libraries.

**Comment by srprasanna** [comment]
Duplicate of https://github.com/Sunbird-RC/community/issues/917
